export enum ContentType {
  JSON = "application/json",
  XML = "application/xml",
  HTML = "text/html",
  PLAIN = "text/plain",
  FORM_URLENCODED = "application/x-www-form-urlencoded",
  MULTIPART_FORM_DATA = "multipart/form-data",
  JAVASCRIPT = "application/javascript",
  CSS = "text/css",
  CSV = "text/csv",
  PDF = "application/pdf",
  OCTET_STREAM = "application/octet-stream",
  PNG = "image/png",
  JPEG = "image/jpeg",
  GIF = "image/gif",
  WEBP = "image/webp",
}
